Create threads
irinafomenko/projects pull request #2
Opened 2019-10-09 13:21 UTC by irinafomenko

2019-10-15 12:32 UTC, dobrikov91 commented on Structure.h
> +        List(int n, List* head, std::string com): prev(NULL)
Дефолтное сокращение от command = cmd. Com отсылает к старым-добрым ком-портам компьютера и заставляет задуматься. Фиксить не обязательно, просто прими к сведению что обычно используются сокращения без гласных букв - cmd, prv, nxt и так далее. Также удобно использовать более расширенное описание во входных параметрах чтобы избежать повторения имен (типа input_command)

2019-10-15 14:45 UTC, dobrikov91 commented on Structure.h
> +    virtual List* head_element_queue() {return begin;}
Две функции извлечения головного элемента выглядят странно. Тем более, что название второй мало о чем говорит. Предлагаю сделать либо новую структуру типа Data{string, int} либо обернуть это просто в пару pair <string, int> и возвращать ее в функциях head и end.
Еще раз насчет названий. head и end - это два слова из разных областей (голова и конец).
Антонимы к ним будут head-tail и begin-end. Советую для имен функций выбирать названия аналогичные СТЛ очереди\дэку http://www.cplusplus.com/reference/queue/queue/
-
И сразу вопрос, чем deque.end() отличается от deque.back() в стльном контейнере?

2019-10-16 14:54 UTC, irinafomenko commented on Structure.h
> +    virtual List* head_element_queue() {return begin;}
deque.back() последний элемент дэка.
deque.end() возвращает последний итератор, его обычно используют в цикле

2019-10-16 19:21 UTC, dobrikov91 commented on Structure.h
> +public:
Так как ты больше не используешь List за пределами очереди, то можно снова сделать его protected

2019-10-16 19:26 UTC, dobrikov91 commented on class_myqueue.h
> +    void push(std::string com)
Вместо двух функций push можно использовать одну использующую значения по умолчанию для входных параметров. Здесь пример работы с ними https://ravesli.com/urok-103-parametry-po-umolchaniyu/ также еще погугли сама

2019-10-16 19:28 UTC, dobrikov91 commented on class_myqueue.h
> +    List* end_element_string()
Наверно ты это уже пофиксила, но снова следи за именами. head_element_QUEUE и end_element_STRING причем ни один суффикс не имеет отношения к возращаемому значению (List)

2019-10-16 19:33 UTC, dobrikov91 commented on main.cpp
> +myQueue* my_command = new myQueue;
А почему эти переменные стали глобальными?)

2019-10-16 19:43 UTC, dobrikov91 commented on queue_menu.cpp
> +// Created by ifomenko on 04.10.2019.
А что планировалось в этих файлах?

2019-10-16 19:44 UTC, dobrikov91 requested changes

2019-10-16 19:44 UTC, dobrikov91 commented on main.cpp
> +    if(argc>1)
Эту инитку можешь снести, т.к. в рамках текущего занятия она смысла не имеет

2019-10-17 09:13 UTC, irinafomenko commented on main.cpp
> +myQueue* my_command = new myQueue;
Я туда их добавила, чтобы не передавать в функции потоков.

2019-10-17 09:15 UTC, irinafomenko commented on queue_menu.cpp
> +// Created by ifomenko on 04.10.2019.
ничего не планировалось, я туда отправила старое меню

2019-10-21 17:35 UTC, dobrikov91 approved these changes
Окей, можешь сливать изменения

2019-10-22 06:58 UTC, merged