Created client and server
irinafomenko/projects pull request #3
Opened 2019-10-31 13:16 UTC by irinafomenko

2019-10-31 23:23 UTC, dobrikov91 commented on CMakeLists.txt
> +add_executable(spisok_2 main.cpp Logger.h Structure.h my_exceptions.h class_myqueue.h class_deque.h server.cpp client.cpp server.h client.h class_myqueue.cpp class_deque.cpp)
Откуда здесь появились cpp файлы, если мы не собираем отдельные приложения для клиента и сервера?

2019-10-31 23:23 UTC, dobrikov91 commented on Structure.h
> +        //std::sring command;
Очепятка?

2019-10-31 23:27 UTC, dobrikov91 commented on class_deque.cpp
> +    if(size != 1)
Неочевидное условие. Для чего оно здесь существует? (ответь в комментах)

2019-10-31 23:29 UTC, dobrikov91 commented on class_deque.cpp
> +        logg_deque.print("Return begin element");
Здесь также стоит печатать значение.

2019-10-31 23:29 UTC, dobrikov91 commented on class_deque.cpp
> +        logg_deque.print("Return end element");
Тоже что и в бегин()

2019-10-31 23:32 UTC, dobrikov91 commented on class_deque.cpp
> +void myDeque::push(int n)
Как я понимаю, функция называется просто push а не push_back из-за наследования?

2019-10-31 23:34 UTC, dobrikov91 commented on class_deque.cpp
> +    logg_deque.print("Return size of queue");
Опять же можно в логи добавить возвращаемый размер

2019-10-31 23:36 UTC, dobrikov91 commented on class_deque.cpp
> +    std::string queue;
А почему строка называется "очередь" если пишем в нее дэк?)

2019-10-31 23:37 UTC, dobrikov91 commented on class_deque.h
> +    void pop();
Советую одинаковые по смыслу функции размещать рядом. (править не обязательно)

2019-10-31 23:38 UTC, dobrikov91 commented on class_myqueue.cpp
> +    }*/
Многострочные комментарии старого кода перед пуллом стоит сносить, если они точно не нужны

2019-10-31 23:39 UTC, dobrikov91 commented on class_myqueue.cpp
> +void myQueue::push(std::string com, int n)
Если из очереди ты достаешь пару, то и класть желательно тоже пару, чтобы не было путаницы в типах.

2019-10-31 23:48 UTC, dobrikov91 commented on class_myqueue.cpp
> +    if(begin != NULL)
В функции хэда ты проверяешь граничное условие на неравенство, а в функции поп - на равенство. Какого-то кодстайла в этой области нет, но я бы советовал придерживаться одного стиля.

2019-10-31 23:49 UTC, dobrikov91 commented on class_myqueue.cpp
> +    logg_queue.print("Return size of queue");
Также выводить значение

2019-10-31 23:50 UTC, dobrikov91 commented on client.cpp
> +#include <functional>
Для новых хидеров сделай комментарии по какой причине они подключены?

2019-10-31 23:54 UTC, dobrikov91 commented on client.cpp
> +        int size_cmd = el.first.length();
Что произойдет в этой строчке, если получение хэда выполнилось с исключением?

2019-10-31 23:58 UTC, dobrikov91 commented on client.cpp
> +        if(el.first == "pop") {deque_pop++;}
Для чего служат эти счетчики?

2019-10-31 23:59 UTC, dobrikov91 commented on client.cpp
> +        if(el.first == "begin_element") {deq_element->push("begin_element");}
Советую разделять пустой строкой различные блоки программы. Для меня было не очевидно, что этот иф не относится к предыдущим строкам.

2019-11-01 00:02 UTC, dobrikov91 commented on client.cpp
> +        if( !strcmp(msg_exception, "yes"))
Эта проверка на исключение у тебя встречается 3 раза. Думаю стоит вынести ее в отдельную функцию

2019-11-01 00:05 UTC, dobrikov91 commented on client.cpp
> +    }
Общий вопрос. Соблюдается ли последовательность команд? Я вижу 3 цикла (поп, сайз и принт) которые идут один за другим. Если я запрошу команды "принт" "поп" "сайз" результат придет в такой же последовательности?

2019-11-01 00:06 UTC, dobrikov91 commented on client.cpp
> +void thread_for_send_to_server(const char *ip_addr)
Отлично, именно то решение, что я и ожидал, молодец)

2019-11-01 00:06 UTC, dobrikov91 commented on client.cpp
> +                my_command->push( "pop");
Эти пробелы перед скобкой меня смущают

2019-11-01 00:16 UTC, dobrikov91 commented on server.cpp
> +        perror("socket");
Эта ошибка пишется в логи?

2019-11-01 00:16 UTC, dobrikov91 commented on server.cpp
> +        perror("bind");
Тоже вопрос про логи.

2019-11-01 00:17 UTC, dobrikov91 commented on server.cpp
> +        if((sock = accept(listener, NULL, NULL)) >= 0);//создает для общения с клиентом новый сокет
Это условие не работает. Почему?

2019-11-01 00:17 UTC, dobrikov91 commented on server.cpp
> +            cout << "New client connected! " << ip_addr_client << endl;
Снова вопрос про логи

2019-11-01 00:20 UTC, dobrikov91 commented on server.cpp
> +                    send(sock, &size_have_elements, sizeof(int), 0);
Интересное решение с передачей размера буфера. А оно точно необходимо, или можно делать все одной командой?

2019-11-01 00:24 UTC, dobrikov91 commented on server.cpp
> +        if(bytes_size_queue <= 0) {break;}
А в каком случае размер очереди может быть отрицательный?

2019-11-01 00:26 UTC, dobrikov91 commented on server.cpp
> +        log_server.print("Connection closed"); // класс Logger
Этот лог пишется в глобальном вайл(1). Оно не приводит к бесконечной записи в логи этой строчки?

2019-11-01 00:26 UTC, dobrikov91 requested changes
Не спеши вносить правки, сначала ответь на вопросы. Тут еще должна Аня поревьювить

2019-11-01 07:43 UTC, irinafomenko commented on Structure.h
> +        //std::sring command;
ага, очепятка

2019-11-01 07:45 UTC, irinafomenko commented on class_deque.cpp
> +void myDeque::push(int n)
да

2019-11-01 07:48 UTC, irinafomenko commented on client.cpp
> +        int size_cmd = el.first.length();
Ошибка. Элемента el.first не будет

2019-11-01 07:49 UTC, irinafomenko commented on client.cpp
> +    }
результат придет в той последовательности, в которой пользователь ее запросил

2019-11-01 07:50 UTC, irinafomenko commented on server.cpp
> +        perror("socket");
нет, добавлю

2019-11-01 07:55 UTC, irinafomenko commented on server.cpp
> +        if((sock = accept(listener, NULL, NULL)) >= 0);//создает для общения с клиентом новый сокет
Работает. Если функция accept возвращает -1, то подключения нет. А так подключается клиент и сервер кидает ему ответное сообщение

2019-11-01 07:57 UTC, irinafomenko commented on server.cpp
> +                    send(sock, &size_have_elements, sizeof(int), 0);
Да, чтобы клиент знал, какого размера читать сообщение

2019-11-01 08:02 UTC, irinafomenko commented on server.cpp
> +        if(bytes_size_queue <= 0) {break;}
Если произошла ошибка приема, то recv возвращает -1

2019-11-01 08:04 UTC, irinafomenko commented on server.cpp
> +        log_server.print("Connection closed"); // класс Logger
Сообщение логируется, только тогда, когда клиент отключается.

2019-11-01 08:06 UTC, irinafomenko commented on class_deque.cpp
> +    std::string queue;
Я ее создала в классе очереди, не поменяла в дэке

2019-11-01 08:51 UTC, irinafomenko commented on class_deque.cpp
> +    if(size != 1)
если дэк состоит не из одного элемента, то нужно сделать нулевую ссылку на следующий.

2019-11-01 09:46 UTC, dobrikov91 commented on client.cpp
> +        int size_cmd = el.first.length();
А почему тогда выполнение команд продолжается после кэтча?

2019-11-01 09:50 UTC, dobrikov91 commented on server.cpp
> +        if((sock = accept(listener, NULL, NULL)) >= 0);//создает для общения с клиентом новый сокет
Для начала, что происходит про условии <0?

2019-11-01 10:06 UTC, irinafomenko commented on server.cpp
> +        if((sock = accept(listener, NULL, NULL)) >= 0);//создает для общения с клиентом новый сокет
До меня вроде бы дошло...Когда клиент подключается, условие выполняется. А когда клиент не подключается, то и дальше мы не идем. В общем, тут это условие лишнее

2019-11-09 12:58 UTC, dobrikov91 commented on .idea/misc.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Удали потом файлы конфиге Слайона из репы

2019-11-11 09:40 UTC, AnnaSagina commented on Logger.h
>          //std::cerr << "Opening log file." << std::endl;
почему     std::ofstream log_file; public?
т.е. у нас кто угодно может фигачить в файл в обход мьютекса?

2019-11-11 09:40 UTC, AnnaSagina commented on Logger.h
>          //always append to the EOF since we need to save all our logs
1) что если в void print(std::string str)  оператор << выбросит эксепшн? мьютекс навсегда залочен?

2019-11-11 09:40 UTC, AnnaSagina commented on Logger.h
>          //std::cerr << "Opening log file." << std::endl;
ну и просто.. зачем?

2019-11-11 09:40 UTC, AnnaSagina commented on Logger.h
> -        comment = cmt;
а почему переместили?

2019-11-11 09:40 UTC, AnnaSagina commented on Logger.h
>                  //print time with log messages to detect when event happens
Тут нужно избавиться от дублирования. Мы фактически два раза формирует строку для печати. Если вдруг понадобится менять ее формат - нужно будет делать это в двух местах, что может привести к ошибкам. Давайте сразу писать удобный код :)

if(comment != NULL)
{
//print time with log messages to detect when event happens
log_file << t << " | " << comment << " | " << str << std::endl;
}
else
{
//print time with log messages to detect when event happens
log_file << t << " | " << str << std::endl;

2019-11-11 09:40 UTC, AnnaSagina commented on Logger.h
>                  //print time with log messages to detect when event happens
вообще, есть несколько способов этого избежать. мне больше всего нравится вариант с заданием по умолчанию пустого коммента "" вместо того, чтобы хранить NULL

2019-11-11 09:40 UTC, AnnaSagina commented on Structure.h
>          List(): next(NULL), prev(NULL){};
меня смущает List(int n, List* head): prev(NULL)
мы не можем верить на слово, что в head лежит именно n элементов, если передадут что-то не то - это может привести к проблемам. нужна проверка

2019-11-11 09:40 UTC, AnnaSagina commented on Structure.h
>          List(): next(NULL), prev(NULL){};
остальные конструкторы тоже проанализировать бы и добавить error handling

2019-11-11 09:40 UTC, AnnaSagina commented on class_deque.cpp
> +extern myexception ex2;
ии все еще не очень понимаю, почему мы швыряемся одним и тем же эесепшном, ане создаем новый обьект для каждой ситуации. если я уже спрашивала - сори,скажите еще раз)

2019-11-11 09:40 UTC, AnnaSagina commented on class_deque.cpp
> +    size++;
если у нас внутри принта вылетит исключение ()а мы его не перехватываем ни там, ни тут), размер не будет увеличен...

2019-11-11 09:40 UTC, AnnaSagina commented on class_deque.cpp
> +    }
опять опять дублирование дублирование :)

2019-11-11 09:40 UTC, AnnaSagina commented on class_deque.cpp
> +int myDeque::size_of_queue()
краткость - сестра таланта) почему не просто size()?

2019-11-11 09:40 UTC, AnnaSagina commented on class_deque.cpp
> +    logg_deque.print("Return size of queue");
size of queue" -> size of Deque

2019-11-11 09:40 UTC, AnnaSagina commented on class_deque.cpp
> +    logg_deque.print("Return size of queue");
и 2. зачем опять реализовывать это в деке, если под не отличается от родительского класса?
3. если бы имя было size, не возникало бы вопросов, почему у объекта типа Дек мы смотрим размер очереди

2019-11-11 09:40 UTC, AnnaSagina commented on class_deque.cpp
> +{
Одна из фич наследования - переиспользование кода, зачем писать то же самое еще раз, если в родительском этот метод уже есть и содержимое принципиально не отличается?

2019-11-11 09:40 UTC, AnnaSagina commented on class_deque.cpp
> +Logger logg_deque("log_example.txt", "Deque");
1. в чем смысл двух разных логгеров (logg_deque и logg_queue) в один и тот же файл? с разными дескрипторами этого файла. как оно вообще работает одновременно для дека и очереди?
2. Если префикс "Deque" ограницивает смысл использования этого логгера классом Дек, и не используется никем снаружи, не имеет ли смысл сделать его статик полем класса ?

2019-11-11 09:40 UTC, AnnaSagina commented on class_myqueue.cpp
> +    }*/
они навсегда в истории гита, так что можно смело сносить

2019-11-11 09:40 UTC, AnnaSagina commented on class_deque.cpp
> +    std::string queue;
если в классе очеереди то же самое, зачем этот метод?

2019-11-11 09:40 UTC, AnnaSagina commented on client.cpp
> +    char msg_exception[size_msg_exception];//для проверки вывода исключения
чему тут равен size_msg_exception ?

2019-11-11 09:40 UTC, AnnaSagina commented on client.cpp
> +    while(my_command->size_of_queue() != 0)
у нас разве в my_command что-то лежит? мы зайдем хоть раз в этот цикл?

2019-11-11 09:40 UTC, AnnaSagina commented on client.cpp
> +void send_to_server(const char *ip_addr)
на несчастный Send навесили кучу дополнительных функций внутри, в результате Send не просто отправляет на сервер, но устанавливает подключение, что-то шлет, принимает, обрабатывает... не очевидно из названия и не есть хороший код стайл. Разделяйте ответственность.

2019-11-11 09:40 UTC, AnnaSagina commented on client.cpp
> +        if(el.first == "begin_element") {deq_element->push("begin_element");}
а еще различные блоки программы можно разделять по разным функциям)

2019-11-11 09:40 UTC, AnnaSagina commented on client.cpp
> +        int el;
ну серьезно, на сколько экранов эта функция?  многабукаф и нить повествования потеряна...

2019-11-11 09:40 UTC, AnnaSagina commented on client.cpp
> +    while(my_command->size_of_queue() != 0)
я дочитала до конца, вопрос снимается:)

2019-11-11 09:40 UTC, AnnaSagina commented on main.cpp
>  #include "Logger.h"
плюсик, за приведенный в порядок main.cpp 🥇

2019-11-11 09:40 UTC, AnnaSagina commented on server.cpp
> +                if (k.first == "pop")
давайте избавляться от строковых констант и выносить их  константы обычные.
а в данном случае, можно заменить на enum, например, и использовать красивый switch

2019-11-11 14:38 UTC, dobrikov91 commented on class_deque.cpp
> +Logger logg_deque("log_example.txt", "Deque");
1. Особенности реализации кода. Часть функций дэка была унаследована из очереди без переопределения, так что когда вызывается дэк.пуш в логи пишется функция как если бы она была вызвана из класса очереди. Не трогайте костыли, а то сломается)
2. Имеет)

2019-11-11 14:40 UTC, dobrikov91 commented on class_deque.cpp
> +int myDeque::size_of_queue()
И уж точно не Deque:size_of_queue)

2019-11-11 14:42 UTC, dobrikov91 commented on class_deque.cpp
> +{
Лень проверять, но вроде очередь комманд теперь содержит пару, а не инт. А крутить шаблоны неохота.

2019-11-12 08:48 UTC, irinafomenko commented on Logger.h
> -        comment = cmt;
привычнее, когда сначала инициализация, а потом выполнение функции

2019-11-12 08:51 UTC, irinafomenko commented on Structure.h
>          List(): next(NULL), prev(NULL){};
тут head это ссылка на следующий элемент, а n новый элемент.

2019-11-12 14:53 UTC, irinafomenko commented on Logger.h
>          //std::cerr << "Opening log file." << std::endl;
Поменяла

2019-11-12 14:53 UTC, irinafomenko commented on class_deque.cpp
> +extern myexception ex2;
Поменяла

2019-11-12 14:54 UTC, irinafomenko commented on class_deque.cpp
> +    size++;
Поправила

2019-11-12 14:54 UTC, irinafomenko commented on class_deque.cpp
> +    }
Поменяла,поменяла)

2019-11-12 14:54 UTC, irinafomenko commented on class_deque.cpp
> +{
функции в классах разные

2019-11-12 14:55 UTC, irinafomenko commented on class_deque.cpp
> +Logger logg_deque("log_example.txt", "Deque");
Костыли не трогала. "Deque" сделала статик полем класса. И "Queue" тоже

2019-11-12 14:55 UTC, irinafomenko commented on client.cpp
> +    char msg_exception[size_msg_exception];//для проверки вывода исключения
переменная инициализируется дальше, поставила туда.

2019-11-12 14:56 UTC, irinafomenko commented on client.cpp
> +        int el;
Поделила)

2019-11-12 14:56 UTC, irinafomenko commented on server.cpp
> +                if (k.first == "pop")
Добавила enum и красивые свитчи

2019-11-12 14:56 UTC, irinafomenko commented on main.cpp
>  #include "Logger.h"
Ура)

2019-11-12 15:02 UTC, irinafomenko commented on client.cpp
> +        if( !strcmp(msg_exception, "yes"))
Вынесла

2019-11-12 15:03 UTC, irinafomenko commented on class_deque.cpp
> +    std::string queue;
в классе очереди нет этой функции

2019-11-15 04:16 UTC, dobrikov91 commented on CMakeLists.txt
> +add_executable(spisok_2 main.cpp Logger.h Structure.h my_exceptions.h class_myqueue.h class_deque.h  server.h client.h class_myqueue.cpp class_deque.cpp enum_commands.h class_connect.h class_connect.
следи за появлением тут срр файлов

2019-11-15 04:21 UTC, dobrikov91 commented on class_connect.cpp
> +    return accept(listener, NULL, NULL);
тут логер имеет мало смысла т.к. операция выполняется после всего логгирования
В таком случае стоит ввести переменную res = accept() между логами и возвращать ее после выхода из функции.

2019-11-15 04:26 UTC, dobrikov91 commented on class_connect.cpp
> +    struct sockaddr_in addr;//адрес
У тебя теперь есть две переменные аддр - здесь и в объявлении класса. Инициализация в обеих функциях одинаковая, так что думаю эта переменная лишняя

2019-11-15 04:33 UTC, dobrikov91 commented on client.cpp
> +                    deq_element->push(el);
А эти 6 одинаковых операций можно как-то ужать в одну строчку?

2019-11-15 04:36 UTC, dobrikov91 commented on client.cpp
> +        cout << "9 - Quit" << endl;
Здесь стоит использовать значения енума чтобы избежать возможных ошибок

2019-11-15 04:38 UTC, dobrikov91 commented on client.cpp
> +                break;
И снова с енумом можно было бы сократить этот свитч в несколько раз

2019-11-15 04:43 UTC, dobrikov91 commented on server.h
> +void main_server(const char *ip_addr);
Перечислены не все функции, которые есть в сервер.цпп

2019-11-15 04:44 UTC, dobrikov91 requested changes
Закрывай последние комменты и закончим уже с этой ревьюхой)

2019-11-15 15:01 UTC, irinafomenko commented on CMakeLists.txt
> +add_executable(spisok_2 main.cpp Logger.h Structure.h my_exceptions.h class_myqueue.h class_deque.h  server.h client.h class_myqueue.cpp class_deque.cpp enum_commands.h class_connect.h class_connect.
поправила

2019-11-15 15:01 UTC, irinafomenko commented on class_connect.cpp
> +    return accept(listener, NULL, NULL);
добавила переменную

2019-11-15 15:02 UTC, irinafomenko commented on class_connect.cpp
> +    struct sockaddr_in addr;//адрес
убрала

2019-11-15 15:02 UTC, irinafomenko commented on client.cpp
> +                    deq_element->push(el);
сделала одной строкой

2019-11-15 15:03 UTC, irinafomenko commented on client.cpp
> +        cout << "9 - Quit" << endl;
Поменяла

2019-11-15 15:03 UTC, irinafomenko commented on client.cpp
> +                break;
сократила)

2019-11-15 15:03 UTC, irinafomenko commented on server.h
> +void main_server(const char *ip_addr);
добавила и в clent.h тоже

2019-11-21 12:06 UTC, AnnaSagina commented on Structure.h
>          List(): next(NULL), prev(NULL){};
а, поняла. 
Тогда стоит давать более очевидные имена параметрам)
в этот раз оставь как есть.

2019-11-21 12:18 UTC, AnnaSagina approved these changes

2019-11-21 12:18 UTC, AnnaSagina commented on class_connect.cpp
> +    log_connect.print("connect_for_client()"); // класс Logger
Идея правильная!
А Большая часть дублирования кода с connect_for_server (что ведет к потенциальным ошибкам) должна натолкнуть на еще один вариант разнесения кода по функциям.

2019-11-21 12:18 UTC, AnnaSagina commented on class_connect.cpp
> +    log_connect.print("connect_for_client()"); // класс Logger
Например,
private connect(..), который делает основную часть кода
public client_connect(...) {connect(...)} - вызывает общий коннект и делает что-то свое
public server connect (...) {connect(...) .....}- вызывает общий коннект и делает что-то свое

2019-11-21 12:18 UTC, AnnaSagina commented on class_deque.cpp
> +{
окей)

2019-11-21 12:18 UTC, AnnaSagina commented on class_connect.cpp
> +    log_connect.print("connect_for_client()"); // класс Logger
править не надо, просто как вариант

2019-11-21 12:26 UTC, irinafomenko commented on class_connect.cpp
> +    log_connect.print("connect_for_client()"); // класс Logger
ооо, поняла)

2019-12-02 03:43 UTC, dobrikov91 approved these changes
Отревьювил, можешь мержить)

2019-12-02 07:17 UTC, merged